// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
......fff.......
.....fbbf.......
....fbbcbf......
...fc1bbbbf.....
..fcc11bbbf.....
..c1c11bbbbf....
..c33311bbbf....
..cc1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcfc..
.cfc111bbcbcccc.
.fbbbbbccbcccdc.
fcdbbbbbbcbcbddc
fdbbbbbbcbbcbbdc
fbbfcbbbbbbccbbf
fbccccbbbbbfffcf
fccdcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....fccff.......
....fcbfcc......
...fbcbbddc.....
..fbbccbbbc.....
.fbbcfffbbbc....
.fbff...fcbc....
.ff.......cc....
................
................
`;
            case "image3":
            case "myImage1":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image4":
            case "EnemyBullet":return img`
. . 2 2 . . 
. 2 2 2 2 . 
2 2 2 2 2 2 
2 2 2 2 2 2 
. 2 2 2 2 . 
. . 2 2 . . 
`;
            case "image2":
            case "PlayerBullet":return img`
. . 4 4 . . 
. 4 4 4 4 . 
4 4 4 4 4 4 
4 4 4 4 4 4 
. 4 4 4 4 . 
. . 4 4 . . 
`;
            case "image5":
            case "LaserPixel":return img`
2 2 2 
2 2 2 
2 2 2 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
